### ISSUE TITLE
Require Flash Algorithm for W806 development board

### ISSUE THREAD

**Issue by nyh-workshop** [henrycoding/cklink-lite#2]
Hello,

Thank you for the CKLink-Lite - I have successfully placed it inside my BluePill and the CDK detects it well.

However, it could not attempt any  download or debug due to the absence of the "Flash Algorithm" specific to the W806 board. The tutorials which uses the CKLink-Lite (https://bbs.elecfans.com/jishu_2180011_1_1.html) requires this extra W806_Flash_Tool.elf file.

Unfortunately, this W806_Flash_Tool.elf could not be downloaded elsewhere except in China.

It is much appreciated if we can have links for this extra ELF file. :)

**Comment by henrycoding** [comment]
Thank you for your attention for this project. 

I collect the elf from https://oshwhub.com/l88889686/cklinkw80x-fang-zhen-qi. But now I don't have the board to test.

If this file is wrong, please notify me as soon as possible,

**Comment by nyh-workshop** [comment]
Hello, I have placed the file inside the CDK and it is working correctly. Thank you for the quick support! :D

**Comment by henrycoding** [comment]
😄, If you like this repository, please star me. Thank you very much!
